### ISSUE TITLE
add `Manager` class to isolate and dispatch detail logic for `puppet-whatsapp`

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#281]
- [x] abstract basic events #284
- [x] cache init / get / release on `manager` #283 
- [x] schedule start / stop on `manager` #285 
- [x] heartbeat start / stop on `manager` # 296
- [x] start / stop related methods on `puppet-whatsapp` #292
- [x] event handler on `puppet-whatsapp` #292
